### ISSUE TITLE
Floating point numbers not matching MySQL exactly

### ISSUE THREAD

**Issue by slominskir** [JeffersonLab/jmyapi#7]
This may be just due to the nature of floating point, but it is worth documenting at least.   Using the PV _iocin1:heartbeat_ with values at 7 digits large demonstrates the issue.  The mysql command line and jmyapi do not match as shown below.  The mysql command line shows additional precision.

Might be a formatting issue, but haven't figured out the magic format command that makes extra precision appear in jmyapi.  It looks like some rounding is occurring.

Compare:
1. mysql command line
```
MySQL [archive]> select time, code, format(val1, 0) from  archive.table_360659 where time >= 426645000255759665 and time <= 426645016093900723;
+--------------------+------+-----------------+
| time               | code | format(val1, 0) |
+--------------------+------+-----------------+
| 426645000255759665 |    0 | 6,479,341       |
| 426645000524195110 |    0 | 6,479,342       |
| 426645000792630555 |    0 | 6,479,343       |
| 426645001061066000 |    0 | 6,479,344       |
| 426645001329501446 |    0 | 6,479,345       |
| 426645001597936891 |    0 | 6,479,346       |
| 426645001866372336 |    0 | 6,479,347       |
| 426645002134807781 |    0 | 6,479,348       |
| 426645002403243227 |    0 | 6,479,349       |
...
```
2. jmyapi via JUnit test case _IntervalServiceTest.testLargeNumbersWithTinyChangeStream_
```
(426645000255759665) 2020-05-13 09:28:00 6479340.0
(426645000524195110) 2020-05-13 09:28:01 6479340.0
(426645000792630555) 2020-05-13 09:28:02 6479340.0
(426645001061066000) 2020-05-13 09:28:03 6479340.0
(426645001329501446) 2020-05-13 09:28:04 6479340.0
(426645001597936891) 2020-05-13 09:28:05 6479350.0
(426645001866372336) 2020-05-13 09:28:06 6479350.0
(426645002134807781) 2020-05-13 09:28:07 6479350.0
(426645002403243227) 2020-05-13 09:28:08 6479350.0
...
```
- [jmyapi (via myquery)](https://epicsweb.jlab.org/myquery/interval?c=iocin1%3Aheartbeat&b=2020-05-13+09%3A28%3A00&e=2020-05-13+09%3A29%3A00&u=&p=&v=1&m=ops&l=100000)

**Note**:  The C++ myapi matches MySQL, so this is specifically a problem with jmyapi.

**Comment by slominskir** [comment]
More evidence this is just the platform differences MySQL warns you about:

https://stackoverflow.com/questions/18551831/java-vs-mysql-float-type-difference

**Comment by apcarp** [comment]
While it doesn't prove anything per se, here is a simple test of java float accuracy on RHEL 7 (same OS as C++ myapi and mysql archiver server).  Note we do not loose accuracy for numbers in the above example, but we do for numbers x10 larger.  This seems to be inline with the above SO's post relative accuracy of ~1/10e7 (i.e. good for about 7 digits).

I believe Tomcat uses the system version of java in our setup.  Is that correct?

# Test environment - on host with production tomcat server
> java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b31)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b31, mixed mode)


Source:
class Main {
	public static void main(String[] args) {
		float f1 = 6479341.0f;
		float f2 = 64793410.0f;
		for(int i = 0 ; i < 10; i++) {
			float v1 = f1 + i;
			float v2 = f2 + i;
			System.out.printf("%f --- %f\n", v1, v2);
		}
	}
}

Output:
6479341.000000 --- 64793408.000000
6479342.000000 --- 64793408.000000
6479343.000000 --- 64793408.000000
6479344.000000 --- 64793412.000000
6479345.000000 --- 64793412.000000
6479346.000000 --- 64793412.000000
6479347.000000 --- 64793416.000000
6479348.000000 --- 64793416.000000
6479349.000000 --- 64793416.000000
6479350.000000 --- 64793416.000000

We've tried several other things, such as retrieving them and storing them as doubles, with no avail.  I guess we can just chalk this up to "platform differences", but it isn't clear to me why that would be the case.

**Comment by slominskir** [comment]
Won't fix.
